print("If you do not have the grade, please enter a / instead of a number")
#Test Average
print("Lets start with your test grades:\n")
testg1 = float(raw_input("Please enter your first grade\n"))
testg2 = float(raw_input("Please enter your second grade\n"))
testg3 = float(raw_input("Please enter your third grade\n"))
testg4 = float(raw_input("Please enter your fourth grade\n"))
testg5 = float(raw_input("Please enter your fifth grade\n"))
sumtestg = (testg1 + testg2 + testg3 + testg4 + testg5)
average1 = (sumtestg/5)
#Homework Average
print("Now for your Homework averae:\n")
workg1 = float(raw_input("Please enter your first grade\n"))
workg2 = float(raw_input("Please enter your second grade\n"))
workg3 = float(raw_input("Please enter your third grade\n"))
workg4 = float(raw_input("Please enter your fourth grade\n"))
workg5 = float(raw_input("Please enter your fifth grade\n"))
sumworkg = (workg1 + workg2 + workg3 + workg4 + workg5)
average2 = (sumworkg/5)
#Quiz Average
print("And now for Quiz average:\n")
quizg1 = float(raw_input("Please enter your first grade\n"))
quizg2 = float(raw_input("Please enter your second grade\n"))
quizg3 = float(raw_input("Please enter your third grade\n"))
quizg4 = float(raw_input("Please enter your fourth grade\n"))
quizg5 = float(raw_input("Please enter your fifth grade\n"))
sumquizg = (quizg1 + quizg2 + quizg3 + quizg4 + quizg5)
average3 = (sumquizg/5)
#participation average
print("Finally, your participation grade. If you are unsure try to quantify how much you think you participated in class as a percent without the %:\n")
partg1 = float(raw_input("Please enter your first grade\n"))
partg2 = float(raw_input("Please enter your second grade\n"))
partg3 = float(raw_input("Please enter your third grade\n"))
partg4 = float(raw_input("Please enter your fourth grade\n"))
partg5 = float(raw_input("Please enter your fifth grade\n"))
sumpartg = (partg1 + partg2 + partg3 + partg4 + partg5)
average4 = (sumpartg/5)
#printing all 4 averages
print("Here is your average\n")
print("Test:"+ str(average1), " Homework:" + str(average2), "Quiz:" + str(average3), "Participation:" + str(average4))
print("Now your weighted average\n")

percent1 = float(raw_input("Please enter your test weighted percent IN DECIMAL FORM EX:45% = 0.45\n"))
percent2 = float(raw_input("Please enter your homework weighted percent IN DECIMAL FORM:\n"))
percent3 = float(raw_input("Please enter your quiz weighted percent IN DECIMAL FORM:\n"))
percent4 = float(raw_input("Please enter your participation weighted percent IN DECIMAL FORM:\n"))

weighted1 = (percent1 * average1)
weighted2 = (percent2 * average2)
weighted3 = (percent3 * average3)
weighted4 = (percent4 * average4)

print("Here is your weighted average\n")
print("Test:" + str(weighted1), "Homework:" + str(weighted2), "Quiz:" + str(weighted3), "Participation:" + str(weighted4))

